/**
 * Utility to get current user information
 * This is a simplified version for the plugin since we can't directly import from care_fe
 */

export interface UserInfo {
  first_name: string;
  last_name: string;
}

/**
 * Get current user from localStorage
 * Care stores user info in localStorage after login
 * Tries multiple possible storage keys
 */
export const getCurrentUser = (): UserInfo | null => {
  try {
    // Try different possible localStorage keys that Care might use
    const possibleKeys = ["currentUser", "user", "authUser"];

    for (const key of possibleKeys) {
      const userJson = localStorage.getItem(key);
      if (userJson) {
        try {
          const user = JSON.parse(userJson);
          if (user && (user.first_name || user.last_name)) {
            return {
              first_name: user.first_name || "",
              last_name: user.last_name || "",
            };
          }
        } catch (e) {
          // Continue to next key
          continue;
        }
      }
    }
  } catch (error) {
    console.warn("Could not retrieve user information:", error);
  }

  // Return null if user not found (will hide "Generated by" field)
  return null;
};
